modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
[[mods]]
modId="l2itemselector"
version="${file.jarVersion}" #mandatory
displayName="L2 Item Selector" #mandatory
logoFile="l2itemselector.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2itemselector]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2itemselector]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2itemselector]]
    modId="l2library"
    mandatory=true
    versionRange="[2.3.4,)"
    ordering="AFTER"
    side="BOTH"